services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx
  php:
    container_name: php-container
    hostname: php
    build: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./logs/php.log:/var/log/fpm-php.www.log
  mariadb:
    image: mariadb
    container_name: mariadb-container
    hostname: mariadb
    env_file:
      - ./env/mariadb.env
    networks:
      - internal
networks:
  internal:
    driver: bridge